version: "3.7"
services: 
  nginx:
    restart: always
    image: nginx:1.19.6-alpine
    container_name: nginx
    depends_on:
      - php8
    volumes: 
      - ./www:/var/www:rw
      - ./services/nginx/conf.d:/etc/nginx/conf.d:rw
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    networks: 
      - default
    command: [nginx-debug, '-g', 'daemon off;']
  php8:
    restart: always
    depends_on: 
      - mysql
      - redis
    build:                           # 构建自定义镜像
      context: ./services/php8/      # 指定Dockerfile文件所在路径
      dockerfile: Dockerfile         # 指定Dockerfile文件名称
    image: php-fpm-8.0.1
    container_name: php8
    tty: true
    volumes: 
      - ./www:/var/www:rw
      - ./services/php8/php.ini:/usr/local/etc/php/php.ini:ro
      - ./logs/php:/var/log/php:rw
    expose: 
      - 9000
    links:
      - mysql
      - redis
    environment: 
      TZ: Asia/Shanghai
    networks:
      - default
    cap_add:
      - SYS_PTRACE
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql57
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes: 
      - ./services/mysql57/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    networks: 
      - default
  redis:
    restart: always
    image: redis:5.0.10
    container_name: redis
    ports: 
      - "6379:6379"
    volumes: 
      - ./services/redis/redis.conf:/usr/local/etc/redis.conf:ro
      - ./data/redis:/data:rw
      - ./logs/redis:/var/log/redis:rw
    command: redis-server --requirepass 123456
    environment:
      TZ: Asia/Shanghai
    networks: 
      - default
 
networks: 
  default:
    driver: bridge